CREATE TABLE registrations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  surname VARCHAR(100) NOT NULL,
  nickname VARCHAR(100) NOT NULL,
  age TINYINT UNSIGNED NOT NULL,
  phone VARCHAR(40) NOT NULL,
  category ENUM('drift', 'race') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
